networks:
  application:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: generic-dashboard-nginx
    ports:
      - "8000:80"
    links:
      - server
    volumes:
      - ./Server:/var/www/html
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./.docker/logs/nginx:/var/logs/nginx:rw
      - /var/www/html/storage
      - /var/www/html/bootstrap/cache
    depends_on:
      - server
      - db
    networks:
      - application
  client:
    image: digizan/generic-dashboard-client:latest
    build:
      context: Client
      dockerfile: Dockerfile
    container_name: generic-dashboard-client
    ports:
      - "5173:5173"
    volumes:
      - ./Client:/app
      - /app/node_modules
    command: "npm run dev -- --host --port 5173"
    networks:
      - application
  server:
    image: digizan/generic-dashboard-server:latest
    build:
      context: Server
      dockerfile: Dockerfile
    container_name: generic-dashboard-server
    ports:
      - "9001:9000"
    volumes:
      - ./Server:/var/www/html
    networks:
      - application
    depends_on:
      - db
  db:
    image: postgres:18.1-alpine
    container_name: generic-dashboard-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=asdqwe123
      - POSTGRES_DB=generic_dashboard
    networks:
      - application
volumes:
  postgres_data: