networks:
  application:
services:
  client:
    image: digizan/generic-dashboard-client:latest
    build:
      context: Client
      dockerfile: Dockerfile
    container_name: generic-dashboard-client
    develop:
      watch:
        - path: ./Client
          target: /app
          ignore:
            - node_modules/
          action: sync
        - path: ./Client/package.json
          target: /app/package.json
          action: rebuild
    ports:
      - "5173:5173"
    volumes:
      #- ./Client:/app
      - /app/node_modules
    command: "npm run dev -- --host --port 5173"
    networks:
      - application
  server:
    image: digizan/generic-dashboard-server:latest
    build:
      context: Server
      dockerfile: Dockerfile
    container_name: generic-dashboard-server
    develop:
      watch:
        - path: ./Server
          target: /var/www/html
          ignore:
            - node_modules/
          action: sync
        - path: ./Server/package.json
          target: /var/www/html/package.json
          action: rebuild
    restart: always
    ports:
      - "3000:3000"
    #volumes:
     # - ./Server:/var/www/html
    networks:
      - application
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: generic-dashboard-db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./Server/database/migrations:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=generic_dashboard_user
      - MYSQL_PASSWORD=Asdqwe123
      - MYSQL_DATABASE=generic_dashboard
      - MYSQL_ROOT_PASSWORD=Asdqwe123
    networks:
      - application
volumes:
  mysql_data: